backs = [
    "90s", 
    "bananas",
    "beach",
    "butterflies",
    "cat",
    "circles",
    "clouds",
    "default",
    "desert",
    "eggs",
    "flowers",
    "forest",
    "galaxy",
    "greatwave",
    "lights",
    "meme",
    "mountain",
    "neko",
    "nightsky",
    "pineapple",
    "pinkcity",
    "pixelcity",
    "pixels",
    "ponyo",
    "rainbowclouds",
    "resort",
    "shapes",
    "simpsons",
    "stevenuniverse",
    "sunset",
    "synthwave1",
    "synthwave2",
    "tokyostreet",
    "town",
    "watermelon",
    "watermelon2",
    "windows"
]
backurl = [
    'https://ibb.co/B2QKQHn',
    'https://ibb.co/mvGnRcS',
    'https://ibb.co/1Xr5d2P',
    'https://ibb.co/qykRswW',
    'https://ibb.co/4Wqfk8c',
    'https://ibb.co/CtsPdqj',
    'https://ibb.co/9bCgfT9',
    'https://ibb.co/cNxxZyQ',
    'https://ibb.co/B4cGRPj',
    'https://ibb.co/mytbNXM',
    'https://ibb.co/zVt1T2f',
    'https://ibb.co/K2ftvvw',
    'https://ibb.co/hVbZ4pF',
    'https://ibb.co/LDKXbNR',
    'https://ibb.co/KLYspsV',
    'https://ibb.co/kDszJJN',
    'https://ibb.co/LQscP9L',
    'https://ibb.co/j8mWMzr',
    'https://ibb.co/sj5Jsyw',
    'https://ibb.co/wSQGgHb',
    'https://ibb.co/bmHMqhj',
    'https://ibb.co/hgCVRfs',
    'https://ibb.co/Mfn4D9v',
    'https://ibb.co/fSkqY3F',
    'https://ibb.co/DD1Nz1c',
    'https://ibb.co/nQ3qqc6',
    'https://ibb.co/t80QvJg',
    'https://ibb.co/0MqVRSb',
    'https://ibb.co/qDvb974',
    'https://ibb.co/60kgK39',
    'https://ibb.co/D5dnCv5',
    'https://ibb.co/s504f5F',
    'https://ibb.co/HGmfySh',
    'https://ibb.co/8gF4Wg2',
    'https://ibb.co/4stRhHX',
    'https://ibb.co/fFyQHgC',
    'https://ibb.co/WWs3fhK'
]
schools = [
    "Bronx Science",
    "Stuyvesant",
    "Brooklyn Tech",
    "Lehman",
    "Brooklyn Latin",
    "LaGuardia",
    "Staten Island Tech",
    "QHSS",
    "HSMSE",
    "Midwood",
    "Goldstein",
    "Townsend Harris",
    "Eleanor Roosevelt",
    "Millennium",
    "Frank Sinatra",
    "Beacon",
    "Bard Queens",
    "Bard Manhattan",
    "Hunter College",
    "McKee",
    "Francis Lewis"
]
boroughs = [
    "Manhattan",
    "Bronx",
    "Brooklyn",
    "Queens",
    "Staten Island",
    "Not in NYC"
]
module.exports = {
	backs, schools, boroughs, backurl
}